### ISSUE TITLE
[Feat]: flash light support?

### ISSUE THREAD

**Issue by ysliew** [ThibaultBee/StreamPack#179]
### Version

2.5.2

### Environment that reproduces the issue

Android SDK 34 on Samsung A series phone

### Use case description

Night time live camera streaming

### Proposed solution

An on screen icon to allow user to toggle flash light on and off

**Comment by ThibaultBee** [comment]
Hi,

This is an SDK and not a real application. The provided demos are not meant to be used as it because they are not fully tested.

In the camera demo, there is already a button to toggle the torch on and off if the torch is available.

In your code, you should have a look at https://github.com/ThibaultBee/StreamPack/blob/3f571f3a751b764f9a8823b00574021a2df3c18f/core/src/main/java/io/github/thibaultbee/streampack/utils/CameraSettings.kt#L91

**Comment by ysliew** [comment]
noted, and it makes perfect sense. thank you.
