### ISSUE TITLE
CameraX use Preview but this lib use AutoFitSurfaceView.How to switch front back camera?

### ISSUE THREAD

**Issue by Squall-Huang** [ThibaultBee/StreamPack#33]
```kotlin
preview.setSurfaceProvider(
                previewView.getSurfaceProvider())
```

Because AutoFitSurfaceView can't get SurfaceProvider, how to switch from back camera to front camera?

**Comment by ThibaultBee** [comment]
Hi,

As a preview view, user shall provide a`Surface` (in the `startPreview`) and not an AutoFitSurfaceView. If you can get a `Surface` from CameraX PreviewView then you can use this `Surface` otherwise you will have to use another type of `Surface` than `PreviewView`. Is there a reason why you want to keep using AndroidX `PreviewView`?

To switch from back to front camera, you can do:
- in `startPreview` set the startup camera with `cameraId = "0"`
-  then use `streamer.camera = "0"`
"0" is the camera id, you can get the full list of camera id with `Context.getCameraList()` or list of back camera with `Context.getBackCameraList()` or list of front camera with `Context.getFrontCameraList()`.

**Comment by Squall-Huang** [comment]
Hi Thibault:
Thank you so much to reply my question and solve my problem.
After I use `startPreview(surface, "1")` , camera change to front.
`streamer.camera = "0"` can swich to back camera.
