### ISSUE TITLE
[Feat]: Background RTMP Streaming

### ISSUE THREAD

**Issue by celouw** [ThibaultBee/StreamPack#74]
### Version

2.5.2

### Environment that reproduces the issue

Emulator

### Use case description

It would be nice to have a background streaming service.

**Comment by ThibaultBee** [comment]
Hi,

Could you described what you are trying to achieve with more details?

FYI:
- There is already a Service for the Screen recorder streamers.
- There isn't a Service for the camera streamer because it is a limitation of Android to access the camera and microphone in a foreground service: see https://developer.android.com/guide/components/foreground-services#bg-access-restrictions.

**Comment by ThibaultBee** [comment]
Stalled. 
Please reopen the issue if you need.

**Comment by celouw** [comment]
Hello, 

sorry for my delayed response... 

Well, in fact, I was testing the client from pedroSG94 and successfully streamed bg content (with locked phone) even with android 13, but got some problems with android 7, API < 26.

About my request, I would use it to stream the content like a security camera, from old phones.

Best regards

**Comment by ThibaultBee** [comment]
Hu, thanks for your answer.
So, I won't add this kind of service for the reason I explained on my previous message: doing so would go against Android guidelines and is not a classic behavior.

But you can create your own service that manages a `Streamer`.
