### ISSUE TITLE
[Bug]: Streaming the SRT video has a lot of lag

### ISSUE THREAD

**Issue by plsmarann** [ThibaultBee/StreamPack#77]
### Version

2.5.2

### Environment that reproduces the issue

samsung galaxy 21+
pixel 6 pro

### RTMP/SRT/... Server

SRT

### Audio configuration

ACC
sampleRate = 44100,
startBitrate = 128000,

### Video configuration

default setting 
resolution: 120x120

### Is it reproducible in the demos application?

No

### Reproduction steps

create stream 
view stream on another android device

### Expected result

low lag video stream

### Actual result

very laggy video stream

**Comment by ThibaultBee** [comment]
Hi,

It could happen for a lot a reasons. The main reason I see here, is that the video bitrate is too high (or bandwidth too small). Could you try to reduce the video bitrate?

If this does not fix your issue, I will have to reproduce the issue.

**Comment by ThibaultBee** [comment]
Ok. It is a stalled issue.
I guess the issue was just the video bitrate.
Starting from 2.6.0, a default video bitrate will be adjust to the video resolution if not specify explicitely.
See https://github.com/ThibaultBee/StreamPack/blob/5ae4592ecfe2e6f5ebcc1d49296bf5f1a068cbf0/core/src/main/java/io/github/thibaultbee/streampack/data/VideoConfig.kt#L187C16-L187C16
